sudo: required

language: ruby
rvm:
	- "2.1.5"

services:
	- docker

before_install:
	- docker build -t tushardwivedi/apihandler .
	- docker run tushardwivedi/apihandler /bin/bash -c "bundle exec rspec"

script:
	- bundle exec rspec
